# Generated by Django 6.0.3 on 2026-07-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
