# Generated by Django 6.0.3 on 2026-07-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_property_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('landlord', 'Landlord'), ('tenant', 'Tenant')], default='buyer', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='interested_in',
            field=models.ManyToManyField(blank=True, related_name='interested_customers', to='accounts.property'),
        ),
    ]
