# Generated by Django 6.0.3 on 2026-07-20 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_block_property_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('lead_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('investor', 'Investor'), ('tenant', 'Tenant')], default='buyer', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('property_listing', 'Property Listing'), ('walk_in', 'Walk-in'), ('phone_call', 'Phone Call'), ('social_media', 'Social Media'), ('other', 'Other')], default='website', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('follow_up', 'Follow Up'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('token', 'Token'), ('converted', 'Converted'), ('lost', 'Closed Lost')], default='new', max_length=20)),
                ('interested_in', models.JSONField(blank=True, default=list)),
                ('area_preferences', models.CharField(blank=True, max_length=500)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bedrooms_min', models.SmallIntegerField(blank=True, null=True)),
                ('bedrooms_max', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms_min', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms_max', models.SmallIntegerField(blank=True, null=True)),
                ('area_sqft_min', models.IntegerField(blank=True, null=True)),
                ('area_sqft_max', models.IntegerField(blank=True, null=True)),
                ('other_requirements', models.TextField(blank=True)),
                ('token_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Lead Created'), ('status_change', 'Status Changed'), ('note', 'Note Added'), ('document', 'Document Added'), ('property', 'Property Shown'), ('token', 'Token Recorded'), ('follow_up', 'Follow-up Scheduled'), ('contacted', 'Contacted')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('payment_slip', 'Payment Slip'), ('invoice', 'Invoice'), ('agreement', 'Agreement'), ('token_receipt', 'Token Receipt'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.lead')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
