# Generated by Django 6.0.3 on 2026-07-26 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_propertyactivity_propertydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Additional agents working on this lead alongside the primary assigned agent.', related_name='collab_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Lead Created'), ('status_change', 'Status Changed'), ('note', 'Note Added'), ('document', 'Document Added'), ('property', 'Property Shown'), ('token', 'Token Recorded'), ('follow_up', 'Follow-up Scheduled'), ('contacted', 'Contacted'), ('collaborator', 'Collaborator Updated')], max_length=30),
        ),
        migrations.CreateModel(
            name='AgentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('deals_target', models.PositiveIntegerField(default=0)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('agent', 'year', 'month')},
            },
        ),
    ]
