# Generated by Django 6.0.3 on 2026-07-31 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_lead_collaborators_property_sold_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The property this lead is negotiating on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.property'),
        ),
        migrations.CreateModel(
            name='BlockRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='accounts.block')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('block', 'name')},
            },
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='requirement',
            field=models.ForeignKey(blank=True, help_text='The block-mandated document requirement this document satisfies, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_documents', to='accounts.blockrequireddocument'),
        ),
    ]
