# Generated by Django 6.0.3 on 2026-08-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_lead_property_blockrequireddocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', help_text='Auto-calculated from requirement completeness and engagement signals on every save.', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('property_listing', 'Property Portals'), ('walk_in', 'Walk-in'), ('phone_call', 'Phone Call'), ('social_media', 'Social Media'), ('other', 'Other')], default='website', max_length=30),
        ),
    ]
