# Generated by Django 6.0.3 on 2026-08-05 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='token_amount',
            new_name='booking_amount',
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='visit_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('received', 'Lead Received'), ('assigned', 'Lead Assigned'), ('contacted', 'Contacted'), ('property_shared', 'Property Shared'), ('follow_up', 'Follow Up'), ('visit_scheduled', 'Visit Scheduled'), ('negotiation', 'Negotiation'), ('booking_confirmed', 'Booking Confirmation'), ('documentation', 'Documentation'), ('payment_tracking', 'Payment Tracking'), ('possession_complete', 'Possession Complete'), ('deal_closed', 'Deal Closed'), ('deal_lost', 'Deal Lost')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Lead Created'), ('status_change', 'Status Changed'), ('note', 'Note Added'), ('document', 'Document Added'), ('property', 'Property Shown'), ('token', 'Token Recorded'), ('follow_up', 'Follow-up Scheduled'), ('contacted', 'Contacted'), ('collaborator', 'Collaborator Updated'), ('visit', 'Site Visit Scheduled'), ('payment', 'Payment Recorded')], max_length=30),
        ),
        migrations.CreateModel(
            name='LeadPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.lead')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
