# Generated by Django 6.0.3 on 2026-08-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_migrate_lead_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total real estate commission owed on this deal. Locked once set.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total sale/deal amount. Locked once set — required before payments can be recorded.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='leadpayment',
            name='payment_against',
            field=models.CharField(choices=[('deal', 'Deal Amount'), ('commission', 'Real Estate Commission')], default='deal', max_length=20),
        ),
        migrations.AddField(
            model_name='leadpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online Transfer'), ('pay_order', 'Pay Order'), ('cheque', 'Cheque')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='leadpayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction ID (online) or cheque/pay order number — required for non-cash methods.', max_length=100),
        ),
    ]
