# Generated by Django 6.0.3 on 2026-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_lead_commission_amount_lead_deal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bikes_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bikes Owned'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cars_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cars Owned'),
        ),
        migrations.AddField(
            model_name='customer',
            name='children',
            field=models.JSONField(blank=True, default=list, help_text='List of children — name, age, school, and class/grade.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='club_membership',
            field=models.CharField(blank=True, help_text='e.g. Karachi Gymkhana, DHA Country & Golf Club, Sindh Club…', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Company / Employer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='evs_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Electric Vehicles Owned'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income_range',
            field=models.CharField(blank=True, choices=[('below_100k', 'Below PKR 100,000/month'), ('100k_300k', 'PKR 100,000 – 300,000/month'), ('300k_500k', 'PKR 300,000 – 500,000/month'), ('500k_1m', 'PKR 500,000 – 1,000,000/month'), ('above_1m', 'Above PKR 1,000,000/month')], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How did they hear about us?', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='residency_status',
            field=models.CharField(blank=True, choices=[('resident', 'Resident Pakistani'), ('overseas', 'Overseas Pakistani'), ('foreign', 'Foreign National')], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='social_media_handle',
            field=models.CharField(blank=True, help_text='Instagram/Facebook handle or profile link — useful for retargeting.', max_length=150),
        ),
    ]
