# Generated by Django 6.0.3 on 2026-08-09 19:50

from django.db import migrations, models


def migrate_counts_to_vehicles(apps, schema_editor):
    """Preserve any existing cars/bikes/EVs counts as placeholder vehicle entries
    (no make/model/year on file for these) before the count fields are dropped."""
    Customer = apps.get_model('accounts', 'Customer')
    for customer in Customer.objects.all():
        vehicles = []
        for count, label in (
            (customer.cars_count, 'Car'),
            (customer.bikes_count, 'Bike'),
            (customer.evs_count, 'Electric Vehicle'),
        ):
            for _ in range(count or 0):
                vehicles.append({'type': label, 'make': '', 'model': '', 'year': ''})
        if vehicles:
            customer.vehicles = vehicles
            customer.save(update_fields=['vehicles'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customer_bikes_count_customer_cars_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicles',
            field=models.JSONField(blank=True, default=list, help_text='List of vehicles owned — type, make, model, and year.'),
        ),
        migrations.RunPython(migrate_counts_to_vehicles, noop),
        migrations.RemoveField(
            model_name='customer',
            name='bikes_count',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cars_count',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='evs_count',
        ),
    ]
