# Generated by Django 6.0.3 on 2026-08-14 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_customer_bikes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('listing', 'List My Property'), ('evaluation', 'Property Evaluation')], default='listing', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Under Review'), ('contacted', 'Contacted'), ('evaluated', 'Evaluated'), ('listed', 'Listed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('plot', 'Plot')], max_length=20)),
                ('purpose', models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=10)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_unit', models.CharField(choices=[('sqft', 'Sq. Ft'), ('sqyd', 'Sq. Yd'), ('marla', 'Marla'), ('kanal', 'Kanal')], default='marla', max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_submissions', to=settings.AUTH_USER_MODEL)),
                ('converted_property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='accounts.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertySubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.propertysubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
