# Generated by Django 6.0.3 on 2026-08-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_propertysubmission_propertysubmissionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.CharField(blank=True, choices=[('', '— No Badge —'), ('top_performer', '🏆 Top Performer'), ('rising_star', '🌟 Rising Star'), ('client_favorite', '❤️ Client Favorite'), ('most_deals', '🤝 Most Deals Closed'), ('veteran', '🎖️ Veteran Agent'), ('team_player', '🙌 Team Player')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='financial_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
