# Generated by Django 6.0.3 on 2026-08-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_badge_user_financial_person_user_legal_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='show_on_website',
            field=models.BooleanField(default=True),
        ),
    ]
