# Generated by Django 6.0.3 on 2026-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_property_show_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='badge',
            field=models.CharField(blank=True, choices=[('', '— No Badge —'), ('hot', '🔥 Hot'), ('featured', '⭐ Featured'), ('new', '🆕 New'), ('price_reduced', '💰 Price Reduced'), ('best_value', '💎 Best Value'), ('exclusive', '👑 Exclusive')], default='', max_length=20),
        ),
    ]
