# Generated by Django 6.0.3 on 2026-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_property_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_listing_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('safepay_environment', models.CharField(choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', max_length=20)),
                ('safepay_api_key', models.CharField(blank=True, help_text='Safepay Client/Public Key', max_length=200)),
                ('safepay_secret_key', models.CharField(blank=True, help_text='Safepay Secret Key', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='featured_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='payment_status',
            field=models.CharField(choices=[('n/a', 'Not Applicable'), ('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed')], default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='safepay_tracker_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='wants_featured',
            field=models.BooleanField(default=False),
        ),
    ]
