# Generated by Django 6.0.3 on 2026-08-16 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_sitesettings_propertysubmission_featured_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluation_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluation_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluation_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluation_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='evaluation_status',
            field=models.CharField(blank=True, choices=[('', 'No Evaluation Yet'), ('pending_approval', 'Pending Admin Approval'), ('approved', 'Approved')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Address emails will appear to be sent from', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
