# Generated by Django 6.0.3 on 2026-08-19 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_propertysubmission_evaluated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='show_to_affiliates',
            field=models.BooleanField(default=True, help_text="Whether affiliates can see this property. Only an admin or the property's own agent can change this."),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliate_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', help_text='Approval workflow state — only meaningful when role is Affiliate.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='The agent who invited this affiliate — only set when role is Affiliate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_affiliates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('manager', 'Sales Manager'), ('admin', 'Admin'), ('affiliate', 'Affiliate')], default='agent', max_length=20),
        ),
    ]
