# Generated by Django 6.0.3 on 2026-08-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_property_show_to_affiliates_user_affiliate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='system_role',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('manager', 'Manager')], max_length=20, null=True, unique=True),
        ),
    ]
