# Generated by Django 6.0.3 on 2026-10-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(choices=[('send', 'Send error'), ('callback', 'Failure callback')], max_length=10)),
                ('error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='accounts.whatsappmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
