# Generated by Django 6.0.3 on 2026-10-02 08:03

from django.db import migrations, models
from django.utils.text import slugify


def fill_slugs_and_publish(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    taken = set()
    for u in User.objects.order_by('pk'):
        base = slugify(f'{u.first_name} {u.last_name}') or slugify(u.email.split('@')[0]) or 'member'
        slug, n = base, 2
        while slug in taken:
            slug, n = f'{base}-{n}', n + 1
        taken.add(slug)
        User.objects.filter(pk=u.pk).update(slug=slug)
    # Keep the website as it is today: publish the 4 members "Meet Our Team" already shows.
    shown = User.objects.filter(is_active=True, role__in=['agent', 'manager']).order_by('first_name')[:4]
    User.objects.filter(pk__in=[u.pk for u in shown]).update(show_on_website=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_whatsappfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_on_website',
            field=models.BooleanField(default=False, help_text='Show this member in "Meet Our Team" on the public website.'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, help_text='Public profile URL (/team/<slug>/), generated from the name.', max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(fill_slugs_and_publish, migrations.RunPython.noop),
    ]
