# Generated by Django 6.0.3 on 2026-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_website_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('property_listing', 'Property Portals'), ('walk_in', 'Walk-in'), ('phone_call', 'Phone Call'), ('social_media', 'Social Media'), ('chatbot', 'Chatbot'), ('other', 'Other')], default='website', max_length=30),
        ),
    ]
