# Generated by Django 6.0.3 on 2026-10-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_lead_source_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='accounts.lead'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='notify_body',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='notify_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='notify_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Who clicked send, for manual sends. Empty for automatic alerts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
